Update build-and-release-apk.yml
Due to
Run r0adkll/sign-android-release@v1
  with:
    releaseDirectory: app/build/outputs/apk/release
    signingKeyBase64: ***
    alias: ***
    keyStorePassword: ***
    keyPassword: ***
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64
    ANDROID_HOME: /usr/local/lib/android/sdk
    ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    export PATH: $PATH:$ANDROID_HOME/build-tools/35.0.0
Preparing to sign key @ app/build/outputs/apk/release with signing key
Found 1 release files.
Error: Couldnt find the Android build tools @ /usr/local/lib/android/sdk/build-tools/29.0.3
Error: Unable to locate executable file: /usr/local/lib/android/sdk/build-tools/29.0.3/zipalign. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.